services:
  alert-webhooks:
    image: alert-webhooks:v1.0.0
    container_name: alert-webhooks
    restart: unless-stopped

    ports:
      - "9999:9999"

    environment:
      # Application settings
      - APP_ENV=development
      - GIN_MODE=release
      - LOG_LEVEL=info

    volumes:
      # Mount configuration files (optional, for easy config updates)
      - ./configs:/app/configs:ro
      - ./templates:/app/templates:ro

      # Mount logs directory (optional, for log persistence)
      - ./logs:/app/logs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.1"

    # Security settings
    user: "1001:1001"
    read_only: true
    tmpfs:
      - /tmp:rw,size=10M

    networks:
      - alert-network

networks:
  alert-network:
    driver: bridge
