apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alert-webhooks-chart.fullname" . }}-secrets
  labels:
    {{- include "alert-webhooks-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # Metric authentication (base64 encoded)
  metric-user: {{ .Values.secrets.metric.user | b64enc | quote }}
  metric-password: {{ .Values.secrets.metric.password | b64enc | quote }}
  
  # Webhooks authentication (base64 encoded)
  webhooks-user: {{ .Values.secrets.webhooks.user | b64enc | quote }}
  webhooks-password: {{ .Values.secrets.webhooks.password | b64enc | quote }}
  
  # Service tokens (base64 encoded)
  telegram-token: {{ .Values.secrets.telegram.token | b64enc | quote }}
  slack-token: {{ .Values.secrets.slack.token | b64enc | quote }}
  discord-token: {{ .Values.secrets.discord.token | b64enc | quote }}
