// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "vincent119@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT",
},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/slack/channel/{channel}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "發送訊息到指定的 Slack 頻道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "發送 Slack 訊息到指定頻道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "頻道名稱 (例如: alerts, emergency)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "發送訊息請求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/slack/channels": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "獲取當前配置的所有 Slack 頻道映射",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "獲取 Slack 頻道配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.ChannelsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/slack/level/{level}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "發送訊息到指定等級對應的 Slack 頻道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "發送 Slack 訊息到指定等級",
                "parameters": [
                    {
                        "type": "string",
                        "description": "等級名稱 (例如: emergency, critical, warning, info)",
                        "name": "level",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "發送訊息請求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/slack/rich/{channel}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "發送包含附件和字段的富文本訊息到指定 Slack 頻道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "發送富文本 Slack 訊息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "頻道名稱 (例如: alerts, emergency)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "富文本訊息請求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.RichMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/slack/status": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "獲取 Slack 服務的當前狀態和配置信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "獲取 Slack 服務狀態",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.StatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/slack/test": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "發送測試訊息到預設頻道以驗證 Slack 連接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "測試 Slack 連接",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/slack/validate/{channel}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "檢查 Bot 是否已加入指定頻道，如果未加入會提供加入指引",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slack"
                ],
                "summary": "驗證 Slack 頻道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "頻道名稱 (例如: alerts, emergency)",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_slack.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/telegram/chatid_{chatid}": {
            "post": {
                "description": "Send message to specified Telegram chat level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telegram"
                ],
                "summary": "Send Telegram message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "聊天等級 (格式: L{0-4})",
                        "name": "chatid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "訊息內容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_telegram.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_telegram.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/telegram/info": {
            "get": {
                "description": "獲取 Telegram 機器人的基本資訊",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telegram"
                ],
                "summary": "獲取機器人資訊",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/discord/channel/{channel}": {
            "post": {
                "description": "Send a message to a specific Discord channel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discord"
                ],
                "summary": "Send message to Discord channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discord Channel ID",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/discord/chatid_L{level}": {
            "post": {
                "description": "Send a message to a Discord channel based on alert level",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discord"
                ],
                "summary": "Send message to Discord level channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alert Level (0-5)",
                        "name": "level",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/discord/status": {
            "get": {
                "description": "Get the status of Discord service and bot information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discord"
                ],
                "summary": "Get Discord service status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.StatusResponse"
                        }
                    }
                }
            }
        },
        "/discord/test/{channel}": {
            "post": {
                "description": "Send a test message to verify channel accessibility",
                "tags": [
                    "discord"
                ],
                "summary": "Test Discord channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discord Channel ID",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/discord/validate/{channel}": {
            "post": {
                "description": "Validate if the bot can access and send messages to the channel",
                "tags": [
                    "discord"
                ],
                "summary": "Validate Discord channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discord Channel ID",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes_api_v1_discord.SendMessageResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "返回伺服器健康狀態",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "健康檢查端點",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "alert-webhooks_pkg_service.Field": {
            "type": "object",
            "properties": {
                "short": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1.ResponseHealthCheck": {
            "type": "object",
            "properties": {
                "Status": {
                    "type": "string"
                },
                "recv_time": {
                    "type": "string"
                },
                "recv_time_utc": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1_discord.SendMessageRequest": {
            "type": "object",
            "properties": {
                "alertmanager_data": {
                    "description": "AlertManager webhook data (wrapped format)",
                    "type": "object",
                    "additionalProperties": true
                },
                "alerts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "commonAnnotations": {
                    "type": "object",
                    "additionalProperties": true
                },
                "commonLabels": {
                    "type": "object",
                    "additionalProperties": true
                },
                "externalURL": {
                    "type": "string"
                },
                "groupKey": {
                    "type": "string"
                },
                "groupLabels": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "description": "Simple text message",
                    "type": "string"
                },
                "receiver": {
                    "description": "Direct AlertManager JSON format (consistent with Slack/Telegram)",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "truncatedAlerts": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1_discord.SendMessageResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "routes_api_v1_discord.StatusResponse": {
            "type": "object",
            "properties": {
                "bot_info": {},
                "error": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1_slack.ChannelsResponse": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "routes_api_v1_slack.RichMessageRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "description": "顏色 (good, warning, danger, 或 hex)",
                    "type": "string"
                },
                "fields": {
                    "description": "字段列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert-webhooks_pkg_service.Field"
                    }
                },
                "footer_icon": {
                    "description": "頁腳圖示",
                    "type": "string"
                },
                "footer_text": {
                    "description": "頁腳文字",
                    "type": "string"
                },
                "icon_emoji": {
                    "description": "自定義 Bot 表情符號",
                    "type": "string"
                },
                "icon_url": {
                    "description": "自定義 Bot 頭像 URL",
                    "type": "string"
                },
                "message": {
                    "description": "訊息內容",
                    "type": "string"
                },
                "title": {
                    "description": "訊息標題",
                    "type": "string"
                },
                "username": {
                    "description": "自定義 Bot 名稱",
                    "type": "string"
                }
            }
        },
        "routes_api_v1_slack.SendMessageRequest": {
            "type": "object",
            "properties": {
                "alertmanager_data": {
                    "description": "AlertManager webhook 數據（包裝格式）",
                    "type": "object",
                    "additionalProperties": true
                },
                "alerts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "commonAnnotations": {
                    "type": "object",
                    "additionalProperties": true
                },
                "commonLabels": {
                    "type": "object",
                    "additionalProperties": true
                },
                "externalURL": {
                    "type": "string"
                },
                "groupKey": {
                    "type": "string"
                },
                "groupLabels": {
                    "type": "object",
                    "additionalProperties": true
                },
                "icon_emoji": {
                    "description": "自定義 Bot 表情符號",
                    "type": "string"
                },
                "icon_url": {
                    "description": "自定義 Bot 頭像 URL",
                    "type": "string"
                },
                "message": {
                    "description": "簡單文字訊息",
                    "type": "string"
                },
                "receiver": {
                    "description": "原始 AlertManager JSON 格式（直接接受）",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "thread_ts": {
                    "description": "線程時間戳（回覆特定訊息）",
                    "type": "string"
                },
                "truncatedAlerts": {
                    "type": "integer"
                },
                "username": {
                    "description": "自定義 Bot 名稱",
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1_slack.SendMessageResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "routes_api_v1_slack.StatusResponse": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "connected": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "routes_api_v1_telegram.Alert": {
            "type": "object",
            "properties": {
                "annotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "endsAt": {
                    "type": "string"
                },
                "fingerprint": {
                    "type": "string"
                },
                "generatorURL": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1_telegram.AlertManagerWebhook": {
            "type": "object",
            "properties": {
                "alerts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes_api_v1_telegram.Alert"
                    }
                },
                "commonAnnotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "commonLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "externalURL": {
                    "type": "string"
                },
                "groupKey": {
                    "type": "string"
                },
                "groupLabels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "receiver": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "truncatedAlerts": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "routes_api_v1_telegram.SendMessageRequest": {
            "type": "object",
            "properties": {
                "alertmanager_data": {
                    "description": "AlertManager webhook 數據",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes_api_v1_telegram.AlertManagerWebhook"
                        }
                    ]
                },
                "message": {
                    "description": "可選，當使用 AlertManager 格式時不需要",
                    "type": "string"
                },
                "template_language": {
                    "description": "可選，優先使用配置檔案中的設定",
                    "type": "string"
                }
            }
        },
        "routes_api_v1_telegram.SendMessageResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "security": [
        {
            "BasicAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Alert Webhooks API",
	Description:      "這是 Alert Webhooks 的 Swagger 文件（由 swag 自動產生）。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
